// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this RobotAccount.
func (mg *RobotAccount) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Permissions); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: mg.Spec.ForProvider.Permissions[i3].Namespace,
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Permissions[i3].NamespaceRef,
			Selector:     mg.Spec.ForProvider.Permissions[i3].NamespaceSelector,
			To: reference.To{
				List:    &ProjectList{},
				Managed: &Project{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Permissions[i3].Namespace")
		}
		mg.Spec.ForProvider.Permissions[i3].Namespace = rsp.ResolvedValue
		mg.Spec.ForProvider.Permissions[i3].NamespaceRef = rsp.ResolvedReference

	}

	return nil
}
